### ISSUE TITLE
distanzAB funktioniert nicht richtig

### ISSUE THREAD

**Issue by TimboBl** [CkFreak/SE3FP#1]
Es sollte für die Entfernung Oslo Hong Kong ca 8000 rauskommen. Das Ergebnis aus meiner Berechnung ist allerdings ca 10000. 
Vielleicht findet jemand den Fehler vor mir

**Comment by sariics** [comment]
Grade aufgestanden und top motiviert

**Comment by TimboBl** [comment]
Heißt das, dass du eine Lösung hast? :D
